CREATE TABLE TRANSACTIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CODE VARCHAR(20),
    AMOUNT DECIMAL(10,2) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL DEFAULT 'CAD',
    DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(20) NOT NULL,
    FOREIGN KEY (CATEGORY) REFERENCES CATEGORIES (CATEGORY),
    FOREIGN KEY (CURRENCY) REFERENCES CURRENCIES (CODE)
);

CREATE TABLE CATEGORIES (
    CATEGORY VARCHAR(20) PRIMARY KEY,
    INCOME INTEGER NOT NULL DEFAULT 0,
    DESCRIPTION VARCHAR(255)
);

CREATE TABLE CURRENCIES (
    CODE VARCHAR(3) PRIMARY KEY
);

INSERT INTO CURRENCIES (CODE) VALUES ('CAD'), ('USD'), ('EUR');
